### ISSUE TITLE
Specifications for how RNN needs input

### ISSUE THREAD

**Issue by nielsrolf** [MuhammadTaha/Predictive-Analysis#14]
- Will one RNN be trained for all stores, or will they be store specific?
- How should the data be split into train/val/test? Split the stores, or give only the first part of each time series as train data?
- How should a train batch look like? Should it be a single time series for one store? If yes, the test and validation data can't be passed at once and the RNN's won't be compatible with our current `AbstractForecaster`. We could define a different interface for them (and maybe merge `AbstractForecaster` with `FeedForward`; the latter adds tensorflow placeholder and session logic mainly)

**Comment by MuhammadTaha** [comment]
I think training data should include all stores or it will reduce the size of dataset

**Comment by raopx** [comment]
@nielsrolf 
1. yes one network on all the stores, although it would make sense to have an identifier of stores in the feature space.
2. the training data should be totally independant of the test data meaning, let's assume we have data from date 1.1.17 to 1.5.17 the network should be trained on for example 2 months of data then tested on the other 3. In other words, split the data per date train the model on older dates then predict the newer. 
3. the train batch could be for the data for each day/month.
