### ISSUE TITLE
Improve Features extraction.

### ISSUE THREAD

**Issue by raopx** [MuhammadTaha/Predictive-Analysis#17]
Hey @MuhammadTaha @nielsrolf @kubraseyhan 

I've done implementing an initial Forecaster using ensamble trees, although the performance is really low, again this is just an initial forecaster that comes out of the box of XGBoost. I'm still working on tweaking it.

so one of the things that we can definitely improve is the extracted features. so let's think about features that would be helpful. one idea that comes to mind is past sales based on the store. 
Meaning for each entry let's assume store is 1 and date is 12.07.2017, in that entry there should be a column defining what were the past sales for that specific store. A variation would be to accumelate based on the day of the week, so mondays would have an aggregated sales for all the past mondays etc. 

please give me your input here.

**Comment by nielsrolf** [comment]
We could add the average per store and weekday (as one number), that would also be a good baseline

**Comment by nielsrolf** [comment]
I still need to replace the estimates for missing features (it's currently always 100 and marked with `#TODO`), but since we want to include this in the model selection process, I would wait until that part is implemented. Then we can find a way to easily integrate that

**Comment by nielsrolf** [comment]
I will add:
- Average sales of the train data for the given store and week day
- Average sales of the train data for the given store and the time of the year (eg for 4.5.2016 and store 19, give the average sales of that store in the days 2.5.-6.5. of all years)

We also discussed that the LSTM and therefore all models should get the sales of the last n days, which can either be their own predictions or data from a lookup in the train data. These features depend on the model, so `next_train_batch(batch_size, forecaster)` will depend on the forecaster

@MuhammadTaha you are working on the data class for the LSTM, which will be used by all models. Can you implement it there? Then I work on the `DataExtraction` class and add the listed features there.
